name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - "src/**"
    - "action.yml"
    - "README.md"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build && npm run package
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
        with:
          ref: 'latest'
          path: 'dist'
      - run: npm install
      - run: npm run build && npm run package
      - name: Setup git
        run: |
          git config --global user.name "FinbertMDS"
          git config --global user.email "ngovanhuy.cntt3@gmail.com"

          cat >$HOME/.netrc <<EOF
          machine github.com
          login FinbertMDS
          password ${GITHUB_TOKEN}
          EOF

      - name: Deploy to latest branch
        working-directory: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Abort job successfully when no scripts updated
          test -z "$(git status --short)" && exit 0

          git add .
          git commit --message "Release for ${GITHUB_SHA}"
          git push origin latest
          
  test-latest:
    runs-on: macos-latest
    needs: [deploy]
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Appium
        uses: FinbertMDS/setup-appium@latest
        with:
          appium-version: "1.20.2"
      - run: appium -v