name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - "src/**"
    - "action.yml"
    - "README.md"
    - ".github/workflows/build.yml"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run build && npm run package
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/checkout@v3
        with:
          ref: 'latest'
          path: 'dist'
      - run: npm install
      - run: npm run build && npm run package
      - name: Setup git
        run: |
          git config --global user.name "FinbertMDS"
          git config --global user.email "ngovanhuy.cntt3@gmail.com"

          cat >$HOME/.netrc <<EOF
          machine github.com
          login FinbertMDS
          password ${GITHUB_TOKEN}
          EOF

      - name: Deploy to latest branch
        working-directory: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Abort job successfully when no scripts updated
          test -z "$(git status --short)" && exit 0

          git add .
          git commit --message "Release for ${GITHUB_SHA}"
          git push origin latest
          
  test-latest:
    runs-on: macos-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Appium
        uses: FinbertMDS/setup-appium@latest
        with:
          appium-version: "1.20.2"
      - run: appium -v